#!/bin/bash

echo "PROJECT_ROOT: $PROJECT_ROOT"
echo "TOKEN_PATIO: $TOKEN_PATIO"
echo "BASE_URL_PATIO: $BASE_URL_PATIO"
echo "IP_LOCAL_MAVPROXY: $IP_LOCAL_MAVPROXY"
echo "IP_REMOTE_MAVPROXY: $IP_REMOTE_MAVPROXY"
echo "PORT_CUBE: $PORT_CUBE"
echo "MEET_LINK: $MEET_LINK"
echo "SCREEN_SESSION_NAME: $SCREEN_SESSION_NAME"
